function data = initADCdata(nCh)

if ~exist('nCh','var')
    nCh=int32(0);
end

data = struct(...
              't',uint64([]), ...
              'amp',uint64([]), ...
              'count',uint32(0), ...
              'nCh',int32(nCh), ...
              'chIdxOrder', int32([4,2,5,3]), ...
              'datetime_start', initDateTime(), ...
              'datetime_end', initDateTime() ...
             );
