function data = initDCSdata(nCh)

if ~exist('nCh','var')
    nCh=int32(0);
end

data = struct(...
              'arrtimes',{cell(nCh,1)}, ...
              'eventtable',{cell(nCh,1)}, ...
              'count',uint32(zeros(nCh,1)), ...
              'nCh',int32(nCh), ...
              'datetime_start', initDateTime(), ...
              'datetime_end', initDateTime() ...
             );
