function paths = getpaths()

paths = {...
    '/', ...
    '/bloodFlowIndxFitting', ...
    '/bloodFlowIndxFitting/Stefan', ...
    '/bloodFlowIndxFitting/Stefan/bruteForce', ...
    '/bloodFlowIndxFitting/TonyAndDavide', ...
    '/bloodFlowIndxFitting/gradients', ...
    '/calcCorrCurve', ...
    '/parseFx3Data', ...
    '/utils' ...
    };



